[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.4"
ark-circom = "0.1"
ark-crypto-primitives = "0.4"
ark-ec = "0.4"
ark-ff = "0.4"
ark-groth16 = "0.4"
ark-serialize = "0.4"
